-- MySQL Script generated by MySQL Workbench
-- Fri Mar 20 22:45:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gemmy_english
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gemmy_english` ;

-- -----------------------------------------------------
-- Schema gemmy_english
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gemmy_english` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `gemmy_english` ;

-- -----------------------------------------------------
-- Table `gemmy_english`.`user_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`user_account` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`user_account` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `join_date` DATETIME NULL DEFAULT NULL,
  `last_login` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`student_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`student_info` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`student_info` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `facebook` VARCHAR(100) NULL DEFAULT NULL,
  `contact_number` VARCHAR(20) NULL DEFAULT NULL,
  `parent_email` VARCHAR(50) NULL DEFAULT NULL,
  `parent_contact_number` VARCHAR(20) NULL DEFAULT NULL,
  `user_account_id` BIGINT NOT NULL,
  `attendance` JSON NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_student_user_account1_idx` (`user_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_user_account1`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `gemmy_english`.`user_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`staff_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`staff_info` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`staff_info` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `facebook` VARCHAR(100) NULL DEFAULT NULL,
  `contact_number` VARCHAR(20) NULL DEFAULT NULL,
  `user_account_id` BIGINT NOT NULL,
  `staff_type` VARCHAR(45) NULL,
  `work_of_staff` VARCHAR(100) NULL,
  `salary` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_staff_info_user_account1_idx` (`user_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_info_user_account1`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `gemmy_english`.`user_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`course` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`course` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`classes` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`classes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `class_name` VARCHAR(45) NOT NULL,
  `class_code` VARCHAR(45) NOT NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `description` VARCHAR(150) NULL DEFAULT NULL,
  `fee` VARCHAR(45) NOT NULL,
  `course_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_class_course1_idx` (`course_id` ASC) VISIBLE,
  UNIQUE INDEX `class_code_UNIQUE` (`class_code` ASC) VISIBLE,
  CONSTRAINT `fk_class_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `gemmy_english`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`role` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`role` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`exam` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`exam` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `exam_type` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`result_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`result_mapping` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`result_mapping` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `band_level` VARCHAR(45) NOT NULL,
  `writing` DOUBLE NULL DEFAULT NULL,
  `speaking` DOUBLE NULL DEFAULT NULL,
  `listening` DOUBLE NULL DEFAULT NULL,
  `reading` DOUBLE NULL DEFAULT NULL,
  `overall` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`exam_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`exam_result` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`exam_result` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `writing` DOUBLE NULL DEFAULT NULL,
  `listening` DOUBLE NULL DEFAULT NULL,
  `reading` DOUBLE NULL DEFAULT NULL,
  `speaking` DOUBLE NULL DEFAULT NULL,
  `overall` DOUBLE NULL DEFAULT NULL,
  `result` VARCHAR(10) NULL DEFAULT NULL,
  `exam_id` BIGINT NOT NULL,
  `student_id` BIGINT NOT NULL,
  `exam_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_exam_result_exam_idx` (`exam_id` ASC) VISIBLE,
  INDEX `fk_exam_result_student1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_exam_result_exam`
    FOREIGN KEY (`exam_id`)
    REFERENCES `gemmy_english`.`exam` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exam_result_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `gemmy_english`.`student_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`fee_payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`fee_payment` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`fee_payment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL DEFAULT NULL,
  `kind_of_payment` VARCHAR(45) NULL DEFAULT NULL,
  `reason` VARCHAR(45) NULL DEFAULT NULL,
  `month` VARCHAR(45) NULL DEFAULT NULL,
  `status` TINYINT NULL DEFAULT NULL,
  `discount` VARCHAR(45) NULL DEFAULT NULL,
  `student_id` BIGINT NOT NULL,
  `classes_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fee_payment_student1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_fee_payment_classes1_idx` (`classes_id` ASC) VISIBLE,
  CONSTRAINT `fk_fee_payment_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `gemmy_english`.`student_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fee_payment_classes1`
    FOREIGN KEY (`classes_id`)
    REFERENCES `gemmy_english`.`classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`user_account_has_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`user_account_has_role` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`user_account_has_role` (
  `user_account_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  PRIMARY KEY (`user_account_id`, `role_id`),
  INDEX `fk_user_account_has_role_role1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_user_account_has_role_user_account1_idx` (`user_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_account_has_role_user_account1`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `gemmy_english`.`user_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_account_has_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `gemmy_english`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`classes_has_staff_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`classes_has_staff_info` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`classes_has_staff_info` (
  `classes_id` BIGINT NOT NULL,
  `staff_info_id` BIGINT NOT NULL,
  PRIMARY KEY (`classes_id`, `staff_info_id`),
  INDEX `fk_classes_has_staff_info_staff_info1_idx` (`staff_info_id` ASC) VISIBLE,
  INDEX `fk_classes_has_staff_info_classes1_idx` (`classes_id` ASC) VISIBLE,
  CONSTRAINT `fk_classes_has_staff_info_classes1`
    FOREIGN KEY (`classes_id`)
    REFERENCES `gemmy_english`.`classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classes_has_staff_info_staff_info1`
    FOREIGN KEY (`staff_info_id`)
    REFERENCES `gemmy_english`.`staff_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`student_classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`student_classes` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`student_classes` (
  `student_info_id` BIGINT NOT NULL,
  `classes_id` BIGINT NOT NULL,
  PRIMARY KEY (`student_info_id`, `classes_id`),
  INDEX `fk_student_info_has_classes_classes1_idx` (`classes_id` ASC) VISIBLE,
  INDEX `fk_student_info_has_classes_student_info1_idx` (`student_info_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_info_has_classes_student_info1`
    FOREIGN KEY (`student_info_id`)
    REFERENCES `gemmy_english`.`student_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_info_has_classes_classes1`
    FOREIGN KEY (`classes_id`)
    REFERENCES `gemmy_english`.`classes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
