-- MySQL Script generated by MySQL Workbench
-- Fri Feb 21 21:32:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gemmy_english
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `gemmy_english` ;

-- -----------------------------------------------------
-- Schema gemmy_english
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gemmy_english` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `gemmy_english` ;

-- -----------------------------------------------------
-- Table `gemmy_english`.`user_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`user_account` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`user_account` (
  `id` BIGINT NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `status` TINYINT NULL,
  `join_date` DATETIME NULL,
  `last_login` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`student_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`student_info` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`student_info` (
  `id` BIGINT NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `birthday` DATETIME NOT NULL,
  `email` VARCHAR(45) NULL,
  `facebook` VARCHAR(45) NULL,
  `contact_number` VARCHAR(10) NULL,
  `parent_email` VARCHAR(45) NULL,
  `parent_contact_number` VARCHAR(10) NULL,
  `user_account_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) VISIBLE,
  INDEX `fk_student_user_account1_idx` (`user_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_user_account1`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `gemmy_english`.`user_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`staff_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`staff_info` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`staff_info` (
  `id` BIGINT NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `birthday` DATETIME NOT NULL,
  `email` VARCHAR(45) NULL,
  `facebook` VARCHAR(45) NULL,
  `contact_number` VARCHAR(10) NULL,
  `user_account_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_staff_info_user_account1_idx` (`user_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_info_user_account1`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `gemmy_english`.`user_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`staff_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`staff_detail` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`staff_detail` (
  `id` BIGINT NOT NULL,
  `staff_type` VARCHAR(45) NULL,
  `work_of_staff` VARCHAR(45) NULL,
  `salary` VARCHAR(45) NULL,
  `staff_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_staff_staff1_idx` (`staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `gemmy_english`.`staff_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`course` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`course` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`class` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`class` (
  `id` BIGINT NOT NULL,
  `start_date` VARCHAR(45) NOT NULL,
  `end_date` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `fee` VARCHAR(45) NOT NULL,
  `course_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_class_course1_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_class_course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `gemmy_english`.`course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`role` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`role` (
  `id` BIGINT NOT NULL,
  `role_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`exam`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`exam` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`exam` (
  `id` BIGINT NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `exam_type` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`result_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`result_mapping` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`result_mapping` (
  `id` INT NOT NULL,
  `band_level` VARCHAR(45) NOT NULL,
  `writing` DOUBLE NULL,
  `speaking` DOUBLE NULL,
  `listening` DOUBLE NULL,
  `reading` DOUBLE NULL,
  `overall` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`exam_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`exam_result` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`exam_result` (
  `id` BIGINT NOT NULL,
  `writing` DOUBLE NULL,
  `listening` DOUBLE NULL,
  `reading` DOUBLE NULL,
  `speaking` DOUBLE NULL,
  `overall` DOUBLE NULL,
  `result` VARCHAR(10) NULL,
  `exam_id` BIGINT NOT NULL,
  `student_id` BIGINT NOT NULL,
  `exam_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_exam_result_exam_idx` (`exam_id` ASC) VISIBLE,
  INDEX `fk_exam_result_student1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_exam_result_exam`
    FOREIGN KEY (`exam_id`)
    REFERENCES `gemmy_english`.`exam` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exam_result_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `gemmy_english`.`student_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`attendance` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`attendance` (
  `date` DATETIME NOT NULL,
  `status` VARCHAR(45) NULL,
  `remark` VARCHAR(45) NULL,
  `student_id` BIGINT NOT NULL,
  `class_id` BIGINT NOT NULL,
  PRIMARY KEY (`date`),
  INDEX `fk_attendance_student1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_attendance_class1_idx` (`class_id` ASC) VISIBLE,
  CONSTRAINT `fk_attendance_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `gemmy_english`.`student_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attendance_class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `gemmy_english`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`fee_payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`fee_payment` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`fee_payment` (
  `id` BIGINT NOT NULL,
  `date` VARCHAR(45) NULL,
  `kind_of_payment` VARCHAR(45) NULL,
  `reason` VARCHAR(45) NULL,
  `month` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `discount` VARCHAR(45) NULL,
  `class_id` BIGINT NOT NULL,
  `student_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fee_payment_class1_idx` (`class_id` ASC) VISIBLE,
  INDEX `fk_fee_payment_student1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_fee_payment_class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `gemmy_english`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fee_payment_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `gemmy_english`.`student_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`student_class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`student_class` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`student_class` (
  `student_id` BIGINT NOT NULL,
  `class_id` BIGINT NOT NULL,
  PRIMARY KEY (`student_id`, `class_id`),
  INDEX `fk_student_has_class_class1_idx` (`class_id` ASC) VISIBLE,
  INDEX `fk_student_has_class_student1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_student_has_class_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `gemmy_english`.`student_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_has_class_class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `gemmy_english`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`class_has_staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`class_has_staff` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`class_has_staff` (
  `class_id` BIGINT NOT NULL,
  `staff_id` BIGINT NOT NULL,
  PRIMARY KEY (`class_id`, `staff_id`),
  INDEX `fk_class_has_staff_staff1_idx` (`staff_id` ASC) VISIBLE,
  INDEX `fk_class_has_staff_class1_idx` (`class_id` ASC) VISIBLE,
  CONSTRAINT `fk_class_has_staff_class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `gemmy_english`.`class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_class_has_staff_staff1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `gemmy_english`.`staff_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gemmy_english`.`user_account_has_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gemmy_english`.`user_account_has_role` ;

CREATE TABLE IF NOT EXISTS `gemmy_english`.`user_account_has_role` (
  `user_account_id` BIGINT NOT NULL,
  `role_id` BIGINT NOT NULL,
  PRIMARY KEY (`user_account_id`, `role_id`),
  INDEX `fk_user_account_has_role_role1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_user_account_has_role_user_account1_idx` (`user_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_account_has_role_user_account1`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `gemmy_english`.`user_account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_account_has_role_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `gemmy_english`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
